CREATE TYPE bid_tt AS TABLE(
bid_id	INT	NULL
,bid_code	NVARCHAR(40)	NULL
,direct_cost	DECIMAL(20)	NULL
,bid_date	DATETIME	NULL
,extended_cost	DECIMAL(20)	NULL
,bid_type_id	INT	NULL
,selling_cost	DECIMAL(20)	NULL
,submission_date	DATETIME	NULL
,project_id	INT	NULL
,project_type_id	INT	NULL
,duration	INT	NULL
,client_id	INT	NULL
,prebid_datetime_conference	DATETIME	NULL
,prebid_venue_conference	NVARCHAR(600)	NULL
,site_datetime_inspection	DATETIME	NULL
,site_venue_inspection	NVARCHAR(600)	NULL
,submission_courier	NVARCHAR(600)	NULL
,submission_email	NVARCHAR(200)	NULL
,submission_hardcopy	NVARCHAR(600)	NULL
,validity_of_bid	DATETIME	NULL
,bid_document_amount	DECIMAL(20)	NULL
,remark	NVARCHAR(0)	NULL
,status_id	INT	NULL)